<a href="https://www.viharatech.com"><img src="https://miro.medium.com/v2/resize:fit:828/format:webp/1*on2Bpj6A5gfd-CzaFOAZRA.jpeg"></a>


- `Welcome to our interactive learning session! In this Jupyter notebook, you'll find a series of questions related to Python Concept. To maximize your learning, please write Python code in the cell below each question and execute it. This hands-on practice will help reinforce your understanding of the concepts. Feel free to reach out if you have any questions or need assistance. Happy coding! 💻🐍 `

Q:1

Which of these about a set is not true?

a) Mutable data type
b) Allows duplicate values
c) Data type with unordered values
d) Immutable data type

  b) Allows duplicate values
  
  c) immutable data type

Q : 2

Create a null vector(list) of size 10 but the fifth value which is 1 ?

In [ ]:
import numpy as np
vector = np.zeros(10,dtype=np.int64)
vector[4] = 1
vector



array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Q : 3

Create a vector(list) with values ranging from 10 to 49 ?

In [ ]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Q : 4
    
Reverse a vector(list)  (first element becomes last) ?

In [ ]:
vector = np.array([1,2,3,4,5])
reverse_vector = vector[::-1]
reverse_vector

array([5, 4, 3, 2, 1])

Q : 5
    
Create a 3x3 matrix with values ranging from 0 to 8  ?   

In [ ]:
matrix = np.arange(0,9).reshape(1,3,3)
matrix

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

Q : 6

Create a 10x10 array with random values and find the minimum and maximum values ?

In [ ]:
values = np.random.rand(10,10)
max_values = np.max(values)
min_values = np.min(values)
print(f'max_values - {max_values}')
print(f'min_values - {min_values}')

max_values - 0.9945476032223406
min_values - 0.008726111528208791


In [ ]:
values = np.random.randint(0,101,(10,10))
max_value = values[0][0]
min_value = values[0][0]

for i in range(10):
  for j in range(10):
    if values[i][j] < min_value:
      min_value = values[i][j]
    if values[i][j] > max_value:
      max_value = values[i][j]
print(values)
print(f'min_value-->{min_value}')
print(f'max_value-->{max_value}')

[[63 46 31 35 18 56 53 38 61 70]
 [97 95 72 77 78 77 96  8 46 97]
 [22 63 99 67 60 60 21 89  6 41]
 [10 88 80 50 70 44 36 98 26 17]
 [90 88 90 58  3 34 95 90 40 65]
 [46  7 59 12 37 82 11 52 53 57]
 [87 75  0  6 30 67 14  1 41 87]
 [ 9 74 80 97 90 53 57 92 21 55]
 [73 19 70 61 76 35 84 43 54 86]
 [75 42 13 98 86 84 96 36 39 97]]
min_value-->0
max_value-->99


Q : 7

Reverse the complete string
----------------------------

a = "i.love.programming.language."

sample output = language programming love i


In [ ]:
a = "i.love.programming.language."
a = a.split('.')
' '.join(a[::-1])

' language programming love i'

Q : 8

task = create an Data Frame that consist values in 6 * 6 manner : index values are ind and columns values are col


ind=['row 1', 'row 2','row 3', 'row 4','row 5', 'row 6']

col=['col 1', 'col 2','col 3', 'col 4', 'col 5', 'col 6']




In [ ]:
import pandas as pd

ind = ['row 1', 'row 2', 'row 3', 'row 4', 'row 5', 'row 6']
col = ['col 1', 'col 2', 'col 3', 'col 4', 'col 5', 'col 6']
df = pd.DataFrame(0, index=ind, columns=col)
print(df)

       col 1  col 2  col 3  col 4  col 5  col 6
row 1      0      0      0      0      0      0
row 2      0      0      0      0      0      0
row 3      0      0      0      0      0      0
row 4      0      0      0      0      0      0
row 5      0      0      0      0      0      0
row 6      0      0      0      0      0      0


Q : 9

Task : Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.


Sample Output =  15  

Double the number of 15 = 30

Triple the number of 15 = 45

Quadruple the number of 15 = 60

Quintuple the number 15 = 75

In [ ]:
def multiply_number(n):
    print(f"Double the number of {n} = {n * 2}")
    print(f"Triple the number of {n} = {n * 3}")
    print(f"Quadruple the number of {n} = {n * 4}")
    print(f"Quintuple the number of {n} = {n * 5}")

num = 15
multiply_number(num)

Double the number of 15 = 30
Triple the number of 15 = 45
Quadruple the number of 15 = 60
Quintuple the number of 15 = 75


Q : 10

Task : Write a Python program to find if a given string starts with a given character using Lambda.

Sample Output:
True
False

In [ ]:
starts_with = lambda string, char: string.startswith(char)


string = input("hello: ")
char = input("h: ")


print(starts_with(string, char))

hello: h
h: true
False


\Q : 11

Task : Swap two Numbers without using 3rd variables



In [ ]:
a = 5
b = 10

print(f"Before swapping: a = {a}, b = {b}")

for i in range(1):
    a = a + b
    b = a - b
    a = a - b

print(f"After swapping: a = {a}, b = {b}")

Before swapping: a = 5, b = 10
After swapping: a = 10, b = 5


Q : 12

Task : Find whether the given number is palindrome or Not


In [ ]:
n = int(input('enter a number '))
temp = n
p = 0
while n > 0:
  rec = n % 10
  p = (p*10) + rec
  n = n // 10
if temp == p:
  print(f'{temp} is a palindram')
else:
  print(f'{temp} is not a palindram')



enter a number 121
121 is a palindram


Q : 13

Task : Write a Python Programme to find whether a given number is Prime number or not


In [ ]:
n = int(input('enter a number '))
count = 0
for i in range(1,n+1):
  if n % i == 0:
    count = count + 1
  if count == 2:
    print(f'{n} is a prime num' )






enter a number 3
3 is a prime num


Q : 14

Task : Write a Python Programme to calculate the number of Digits and Letters in a string

In [ ]:
a = 'python1234'

letter_count = 0
digit_count = 0

for char in a:
  if char.isalpha():
    letter_count += 1
  elif char.isdigit():
    digit_count += 1

print(f'{letter_count} num of letters')
print(f'{digit_count} num if digits')

6 num of letters
4 num if digits


Q : 15

Task :  write a python programme to prove whether the given number is perfect number or not  

In [ ]:
n = int(input('enter a number '))
c = 0
for i in range(1,n+1):
  if n % i == 0:
    c = c + i
if n == c:
  print(f'{n} is perfect')
else:
  print(f'{n} is not perfect')

enter a number 6
6 is not perfect


Q : 16

Task: write a python programme to prove whether the given number is Amstrong number or not

In [ ]:
n = 153
temp = n
a = 0
while n > 0:
  rec = n % 10
  a = a + (rec*rec*rec)
  n = n // 10
if temp == c:
  print(f'{temp} is amstrong')
else:
  print(f'{temp} is not amstrong')


153 is not amstrong


Q : 17

Task :

Given an array of Integers , find the sum of its elements


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5]).sum()
a

15

In [ ]:
a = np.array([1,2,3,4,5])
b = 0
for i in a:
  b += i
print(b)


15


Q : 18

Task :

Write a Python Programme to find the values Divisible by 5 and 3 from 15 to 50

In [ ]:
a = []
for i in range(15,51):
  if i % 5 == 0:
    if i % 3 == 0:
     a.append(i)
print(a)


[15, 30, 45]


Q : 19

Task :

Print 2 Table from 2 * 1 = 2 till 2 * 10 = 20

In [ ]:
a = 2
for i in range(1,11):
  print(f'{a} * {i} = {i*a}')

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


Q : 20

Task :

print all values from 1 to 101 and skip an element 56 from the list

In [ ]:

a = []
for i in range(1,102):
  if i == 56:
    continue
  a.append(i)
print(a)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101]


Q : 21


Task :

Given an integer  n , perform the following conditional actions:

If n is odd, print Weird
If n is even and in the inclusive range of 2 to 5 , print Not Weird
If n is even and in the inclusive range of 6 to 20 , print Weird
If n is even and greater than 20 , print Not Weird



Input Format
-----------------
A single line containing a positive integer, n.

Constraints
-------------

1<=n<=100

Output Format
----------------

Print Weird if the number is weird. Otherwise, print Not Weird.

Sample Input 0
----------------

3

Sample Output 0
-----------------

Weird


Explanation 0
---------------------

n=3  is odd and odd numbers are weird, so print Weird.

Sample Input 1
-------------------------
24

Sample Output 1
-------------------------

Not Weird


Explanation 1
---------------------------

n > 20  and n  is even, so it is not weird.


**Given an integer n , perform the following conditional actions:

**If n is odd, print Weird If n is even and in the inclusive range of 2 to 5 , print Not Weird If n is even and in the inclusive range of 6 to 20 , print Weird If n is even and greater than 20 , print Not Weird

In [ ]:
n = int(input("Enter an integer: "))

for i in [n]:
    if n % 2 == 1:
        print("Weird")
    elif 2 <= n <= 5:
        print("Not Weird")
    elif 6 <= n <= 20:
        print("Weird")
    else:
        print("Not Weird")


Enter an integer: 6
Weird
